/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  skycons.add("today", Skycons.CLEAR_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start all icons animation!
  skycons.play();

  var icon = function(weather, name){
    if(weather === "Sunny" || "Fair (Day)" || "Hot" ){
      skycons.set(name, Skycons.CLEAR_DAY);
    }else if(weather === "Clear (Night)" || "Fair (Night)"){
      skycons.set(name, Skycons.CLEAR_NIGHT);
    }else if(weather === "Cloudy"  || "Partly Cloudy (Day)" || "Partly Cloudy"){
      skycons.set(name, Skycons.PARTLY_CLOUDY_DAY);
    }else if(weather === "Partly Cloudy (Night)"){
      skycons.set(name, Skycons.PARTLY_CLOUDY_NIGHT);
    }else if(weather === "Mostly Cloudy"|| "Mostly Cloudy (Night)" || "Mostly Cloudy (Day)"){
      skycons.set(name, Skycons.CLOUDY);
    }else if(weather === "Rain" || "Tropical Storm" || "hurricane" || "Severe Thunderstorms" || "Thunderstorms" || "Showers" ||"Mixed Rain and Hail" || "Isolated Thunderstorms" || "Scattered Thunderstorms" || "Scattered Showers" || " Thundershowers" || "Isolated Thundershowers"){
      skycons.set(name, Skycons.RAIN);
    }else if(weather === "Mixed Rain and Snow" || "Mixed Rain and Sleet" || "Mixed Snow and Sleet" || "Freezing drizzle" || "Drizzle" || "Freezing Rain" || "Hail" || "sleet"){
      skycons.set(name, Skycons.SLEET);
    }else if(weather === "Snow Flurries" || "Light Snow Showers" || "Blowing Snow" || "Snow" || "Cold" || "Heavy Snow" || "Scattered Snow Showers" || "Snow Showers"){
      skycons.set(name, Skycons.SNOW);
    }else if(weather === "Tornado" || "Dust" || "windy"){
      skycons.set(name, Skycons.WIND);
    }else if(weather === "Foggy" || "Haze" || "Smoky" || "Blustery"){
      skycons.set(name, Skycons.FOG);
    }
  }

/*
Get value from Bootstrap dropdown menu
*/
//function of convert units
var convert = function(x){
  var y;
  y = (x - 32) * 5 / 9;
  return Math.round(y);
}

//function of getting the value
var weather = function(name){
  $.getWeatherJSON(name,function(data){
    // 可以比較方便找到你要的資料在這個物件的哪個位置
    console.log (data) ;
    
    //Forecast
    //date
    var currentDate = data.query.results.channel.item.forecast[0].date;
    var firstDate = data.query.results.channel.item.forecast[1].date;
    var secondDate = data.query.results.channel.item.forecast[2].date;
    var thirdDate = data.query.results.channel.item.forecast[3].date;
    $("#first-day").html(firstDate);
    $("#second-day").html(secondDate);
    $("#third-day").html(thirdDate);

    //high and low temp
    // var currentHigh = data.query.results.channel.item.forecast[0].high;
    // var currentLow = data.query.results.channel.item.forecast[0].low;
    var firstHigh = data.query.results.channel.item.forecast[1].high;
    var firstLow = data.query.results.channel.item.forecast[1].low;
    var secondHigh = data.query.results.channel.item.forecast[2].high;
    var secondLow = data.query.results.channel.item.forecast[2].low;
    var thirdHigh = data.query.results.channel.item.forecast[3].high;
    var thirdLow = data.query.results.channel.item.forecast[3].low;
    $("#first-temp").html(convert(firstHigh)+ '-' + convert(firstLow) + ' &#8451');
    $("#second-temp").html(convert(secondHigh)+ '-' + convert(secondLow) +' &#8451');
    $("#third-temp").html(convert(thirdHigh)+ '-' + convert(thirdLow) + '&#8451');
    var firstText = data.query.results.channel.item.forecast[1].text;
    var secondText = data.query.results.channel.item.forecast[2].text;
    var thirdText = data.query.results.channel.item.forecast[3].text;
    icon(firstText,"day1");
    icon(secondText,"day2");
    icon(thirdText,"day3");
    
    //Current
    var currentTemp = data.query.results.channel.item.condition.temp;
    var currentText = data.query.results.channel.item.forecast[0].text;
    $(".temperature").html(convert(currentTemp));
    $(".condition").html('<span class="date">' + currentDate + '</span>' + ': ' + currentText);
    // // icon(currentText,"today");
    // if(currentText === "Rain" || "Scattered Showers"){
    //   skycons.set("today", Skycons.RAIN);
    // }else if(currentText === "Mostly Cloudy"){
    //   skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
    // }
    // icon(currentText,"today");
    // console.log(secondLow);
   
    });
}
//default city
weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taipei%20city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");


//chose the city
$('#dropdown li').on('click', function(){
  $('.btn').html($(this).text()+' '+'<span class="caret"></span>');
  var city = ($(this).text());
  if(city === "台北市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taipei%20city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "新北市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22new%20taipei%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "台中市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taichung%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "台南市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22tainan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "高雄市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22kaohsiung%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "基隆市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22keelung%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "桃園市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taoyuan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "新竹市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22hsinchu%20city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "新竹縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22hsinchu%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "苗栗縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22miaoli%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "彰化縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22changhua%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "南投縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nantou%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "雲林縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22yunlin%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "嘉義市"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22chiayi%20city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "嘉義縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22chiayi%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "屏東縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22pingtoung%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "宜蘭縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22yilan%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "花蓮縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22hualian%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "台東縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taitung%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "澎湖縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22penghu%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "金門縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22kinmen%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }else if(city === "連江縣"){
    weather("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%20Lienjiang%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
  }
});

// //get the current temperature
// var temp = [];
// var storeTemp = function(city,index, name){
//   $.getJSON(name,function(data){
//     var currentTemp = data.query.results.channel.item.condition.temp;
//     temp[index] = convert(currentTemp);
//     $(city).html($(city).html()+ " " + convert(currentTemp) + " &#8451" );
//   });
// }


// //save the current temp to the list
// storeTemp("#taipei", 0, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taipei%20city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#newTaipei", 1, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22new%20taipei%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#taichung", 2, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taichung%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#tainan", 3, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22tainan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#kao", 4, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22kaohsiung%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#kee", 5, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22keelung%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#taoci", 6, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taoyuan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#hsinci", 7, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22hsinchu%20city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#hsinco", 8, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22hsinchu%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#miao", 9, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22miaoli%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#chang", 10, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22changhua%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#nan", 11, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nantou%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#yun", 12, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22yunlin%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#jiaci", 13, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22chiayi%20city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#jiaco",14, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22chiayi%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#ping", 15, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22pingtoung%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#yi", 16, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22yilan%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#hwa", 17, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22hualian%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#tai", 18, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taitung%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#peng", 19, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22penghu%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#jingmen", 20, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22kinmen%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");
// storeTemp("#lianjiang", 21, "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22%20Lienjiang%20county%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys");


// console.log(temp);
